In [1]:
import pandas as pd

In [2]:
obesitas = pd.read_csv('obesitasclean.csv')

In [3]:
data = obesitas.copy()

In [4]:
data

     Age  Gender  Height  Weight   BMI          Label
0     25    Male     175      80  25.3  Normal Weight
1     30  Female     160      60  22.5  Normal Weight
2     35    Male     180      90  27.3     Overweight
3     40  Female     150      50  20.0    Underweight
4     45    Male     190     100  31.2          Obese
..   ...     ...     ...     ...   ...            ...
103   11    Male     175      10   3.9    Underweight
104   16  Female     160      10   3.9    Underweight
105   21    Male     180      15   5.6    Underweight
106   26  Female     150      15   5.6    Underweight
107   31    Male     190      20   8.3    Underweight

[108 rows x 6 columns]

In [5]:
target = 'Label'

In [6]:
#kolom gender akan di encode menjadi binary true atau false
encode = ['Gender']

In [7]:
for col in encode:
    dummy = pd.get_dummies(data[col], prefix=col)
    data = pd.concat([data,dummy], axis=1)
    del data[col]

In [8]:
data

     Age  Height  Weight   BMI          Label  Gender_Female  Gender_Male
0     25     175      80  25.3  Normal Weight          False         True
1     30     160      60  22.5  Normal Weight           True        False
2     35     180      90  27.3     Overweight          False         True
3     40     150      50  20.0    Underweight           True        False
4     45     190     100  31.2          Obese          False         True
..   ...     ...     ...   ...            ...            ...          ...
103   11     175      10   3.9    Underweight          False         True
104   16     160      10   3.9    Underweight           True        False
105   21     180      15   5.6    Underweight          False         True
106   26     150      15   5.6    Underweight           True        False
107   31     190      20   8.3    Underweight          False         True

[108 rows x 7 columns]

In [9]:
#selanjutntya memetakan label target menjadi numerik
target_mapper = {'Underweight':0, 'Normal Weight':1, 'Overweight':2, 'Obese':3}

In [10]:
def target_encode(val):
    return target_mapper[val]

In [11]:
data['Label'] = data['Label'].apply(target_encode)

In [12]:
data

     Age  Height  Weight   BMI  Label  Gender_Female  Gender_Male
0     25     175      80  25.3      1          False         True
1     30     160      60  22.5      1           True        False
2     35     180      90  27.3      2          False         True
3     40     150      50  20.0      0           True        False
4     45     190     100  31.2      3          False         True
..   ...     ...     ...   ...    ...            ...          ...
103   11     175      10   3.9      0          False         True
104   16     160      10   3.9      0           True        False
105   21     180      15   5.6      0          False         True
106   26     150      15   5.6      0           True        False
107   31     190      20   8.3      0          False         True

[108 rows x 7 columns]

In [13]:
# split data menjadi 2, X dan Y dimana
# X merupakan seluruh dataset tanpa kolom label dan
# Y merupakan data jenis saja
X = data.drop('Label', axis=1)
Y = data['Label']

In [14]:
X

     Age  Height  Weight   BMI  Gender_Female  Gender_Male
0     25     175      80  25.3          False         True
1     30     160      60  22.5           True        False
2     35     180      90  27.3          False         True
3     40     150      50  20.0           True        False
4     45     190     100  31.2          False         True
..   ...     ...     ...   ...            ...          ...
103   11     175      10   3.9          False         True
104   16     160      10   3.9           True        False
105   21     180      15   5.6          False         True
106   26     150      15   5.6           True        False
107   31     190      20   8.3          False         True

[108 rows x 6 columns]

In [15]:
Y

0      1
1      1
2      2
3      0
4      3
      ..
103    0
104    0
105    0
106    0
107    0
Name: Label, Length: 108, dtype: int64

In [16]:
#Memodelkan dataset menggunakan NBC
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, Y)

GaussianNB()

In [17]:
#Menyimpan Model NBC
import pickle
pickle.dump(model,open('modelNBC_obesitas.pkl','wb'))